name: Push
on: [push]

jobs:

  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.4.2']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Check directory contents
        run: ls -la services/scrapper
      - name: Install dependencies
        run: poetry install --no-root
        working-directory: services/scrapper
      - name: Run black
        run: poetry run black . --check -v --config $(pwd)/pyproject.toml
        working-directory: services/scrapper
      - name: Run isort
        run: poetry run isort . --check-only --profile black -v --settings-path $(pwd)/pyproject.toml
        working-directory: services/scrapper
      - name: Run flake8
        run: poetry run flake8 . -v --config $(pwd)/pyproject.toml
        working-directory: services/scrapper
      - name: Run bandit
        run: poetry run bandit . -v -r -c $(pwd)/bandit.yml
        working-directory: services/scrapper
